spring.application.name=esportsbuzz
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.servlet.context-path=/esportsbuzz
jwt.secret=${jwt.secret=}
jwt.expiration={jwt.expiration}
cookie.secure=false
cookie.samesite=Lax

